const colors = require("tailwindcss/colors");

module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    darkMode: "class", // or 'media' or false
    theme: {
        fontFamily: {
            sans: ["cairo", "sans-serif"],
            body: [
                "Inter",
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "system-ui",
                "Segoe UI",
                "Roboto",
                "Helvetica Neue",
                "Arial",
                "Noto Sans",
                "sans-serif",
                "Apple Color Emoji",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
                "Noto Color Emoji",
            ],
            sans: [
                "Inter",
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "system-ui",
                "Segoe UI",
                "Roboto",
                "Helvetica Neue",
                "Arial",
                "Noto Sans",
                "sans-serif",
                "Apple Color Emoji",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
                "Noto Color Emoji",
            ],
            fraunces: ["Fraunces", "sans-serif"],
            europhia: ["Euphoria Script", "sans-serif"],
            protest: ["Protest Riot", "sans-serif"],
            qwigley: ["Qwigley", "sans-serif"],
            alike: ["Alike", "sans-serif"],
            alkatra: ["Alkatra", "sans-serif"],
            marmelad: ["Marmelad", "sans-serif"],
            amiri: ["Amiri", "sans-serif"],
        },

        extend: {
            colors: {
                light: "var(--light)",
                dark: "var(--dark)",
                darker: "var(--darker)",
                kuning: "#FFC600",
                text: "#722F37",
                price: "#4E2A2A",

                primary: {
                    DEFAULT: "var(--color-primary)",
                    50: "var(--color-primary-50)",
                    100: "var(--color-primary-100)",
                    light: "var(--color-primary-light)",
                    lighter: "var(--color-primary-lighter)",
                    dark: "var(--color-primary-dark)",
                    darker: "var(--color-primary-darker)",
                },
                secondary: {
                    DEFAULT: colors.fuchsia[600],
                    50: colors.fuchsia[50],
                    100: colors.fuchsia[100],
                    light: colors.fuchsia[500],
                    lighter: colors.fuchsia[400],
                    dark: colors.fuchsia[700],
                    darker: colors.fuchsia[800],
                },
                success: {
                    DEFAULT: colors.green[600],
                    50: colors.green[50],
                    100: colors.green[100],
                    light: colors.green[500],
                    lighter: colors.green[400],
                    dark: colors.green[700],
                    darker: colors.green[800],
                },
                warning: {
                    DEFAULT: colors.orange[600],
                    50: colors.orange[50],
                    100: colors.orange[100],
                    light: colors.orange[500],
                    lighter: colors.orange[400],
                    dark: colors.orange[700],
                    darker: colors.orange[800],
                },
                danger: {
                    DEFAULT: colors.red[600],
                    50: colors.red[50],
                    100: colors.red[100],
                    light: colors.red[500],
                    lighter: colors.red[400],
                    dark: colors.red[700],
                    darker: colors.red[800],
                },
                info: {
                    DEFAULT: colors.cyan[600],
                    50: colors.cyan[50],
                    100: colors.cyan[100],
                    light: colors.cyan[500],
                    lighter: colors.cyan[400],
                    dark: colors.cyan[700],
                    darker: colors.cyan[800],
                },
            },
        },
    },
    variants: {
        extend: {
            backgroundColor: ["checked", "disabled"],
            opacity: ["dark"],
            overflow: ["hover"],
        },
    },
    plugins: [],
};
